name: Deploy Prod

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VUE_APP_TEST: TEST
#          envkey_VUE_APP_GOOGLE_API_KEY: ${{ secrets.ENVKEY_VUE_APP_GOOGLE_API_KEY }}
#          envkey_VUE_APP_OPENWEATHER_API_KEY: ${{ secrets.ENVKEY_VUE_APP_OPENWEATHER_API_KEY }}
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build:prod
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO --delete -v'
          SOURCE: 'dist/'
          REMOTE_HOST: 64.4.160.12
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: 7822
          TARGET: /var/www/side-projects/wholesome-health
